# Generated by Django 5.2.7 on 2025-10-05 07:59

import django.db.models.deletion
from django.db import migrations, models


def assign_parsed_items(apps, schema_editor):
    Paper = apps.get_model('core', 'Paper')
    ParsedItem = apps.get_model('core', 'ParsedItem')
    count = Paper.objects.count()
    print(f" - Assigning parsed items for {count} papers...")
    for index, paper in enumerate(Paper.objects.all()):
        if index % 100 == 0:
            print(f" - Assigning parsed items for {index + 1} / {count} papers...")
        ParsedItem.objects.create(paper=paper, key='article_type', value=paper.article_type)
        ParsedItem.objects.create(paper=paper, key='description', value=paper.description)
        ParsedItem.objects.create(paper=paper, key='novelty', value=paper.novelty)
        ParsedItem.objects.create(paper=paper, key='limitation', value=paper.limitation)
        ParsedItem.objects.create(paper=paper, key='research_goal', value=paper.research_goal)
        ParsedItem.objects.create(paper=paper, key='research_objects', value=paper.research_objects)
        ParsedItem.objects.create(paper=paper, key='field_category', value=paper.field_category)
        ParsedItem.objects.create(paper=paper, key='disease_category', value=paper.disease_category)
        ParsedItem.objects.create(paper=paper, key='technique', value=paper.technique)
        ParsedItem.objects.create(paper=paper, key='model_type', value=paper.model_type)
        ParsedItem.objects.create(paper=paper, key='data_type', value=paper.data_type)
        ParsedItem.objects.create(paper=paper, key='sample_size', value=paper.sample_size)
    print(f" - Finished assigning parsed items for {count} papers.")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paper_journal_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paper')),
            ],
        ),
        migrations.RunPython(assign_parsed_items),
    ]
