# Generated by Django 5.2.7 on 2025-10-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_parseditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='description',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='disease_category',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='field_category',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='novelty',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='research_goal',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='research_objects',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='sample_size',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='technique',
        ),
    ]
